mia_linea = input("Scrivi qualcosa: ")
print('Lunghezza della riga:', len(mia_linea), 'caratteri')
print(mia_linea.upper())
print(mia_linea.lower())
print(mia_linea.replace(' ', ''))
print(mia_linea[0])
print(mia_linea[-1])